export default {
  status: {
    timestamp: '2024-10-15T17:59:20.595Z',
    error_code: 0,
    error_message: null,
    elapsed: 16,
    credit_count: 1,
    notice: null,
  },
  data: {
    1: {
      id: 1,
      name: 'Bitcoin',
      symbol: 'BTC',
      slug: 'bitcoin',
      num_market_pairs: 11772,
      date_added: '2010-07-13T00:00:00.000Z',
      tags: [
        {
          slug: 'mineable',
          name: 'Mineable',
          category: 'OTHERS',
        },
        {
          slug: 'pow',
          name: 'PoW',
          category: 'ALGORITHM',
        },
        {
          slug: 'sha-256',
          name: 'SHA-256',
          category: 'ALGORITHM',
        },
        {
          slug: 'store-of-value',
          name: 'Store Of Value',
          category: 'CATEGORY',
        },
        {
          slug: 'state-channel',
          name: 'State Channel',
          category: 'CATEGORY',
        },
        {
          slug: 'coinbase-ventures-portfolio',
          name: 'Coinbase Ventures Portfolio',
          category: 'CATEGORY',
        },
        {
          slug: 'three-arrows-capital-portfolio',
          name: 'Three Arrows Capital Portfolio',
          category: 'CATEGORY',
        },
        {
          slug: 'polychain-capital-portfolio',
          name: 'Polychain Capital Portfolio',
          category: 'CATEGORY',
        },
        {
          slug: 'binance-labs-portfolio',
          name: 'Binance Labs Portfolio',
          category: 'CATEGORY',
        },
        {
          slug: 'blockchain-capital-portfolio',
          name: 'Blockchain Capital Portfolio',
          category: 'CATEGORY',
        },
        {
          slug: 'boostvc-portfolio',
          name: 'BoostVC Portfolio',
          category: 'CATEGORY',
        },
        {
          slug: 'cms-holdings-portfolio',
          name: 'CMS Holdings Portfolio',
          category: 'CATEGORY',
        },
        {
          slug: 'dcg-portfolio',
          name: 'DCG Portfolio',
          category: 'CATEGORY',
        },
        {
          slug: 'dragonfly-capital-portfolio',
          name: 'DragonFly Capital Portfolio',
          category: 'CATEGORY',
        },
        {
          slug: 'electric-capital-portfolio',
          name: 'Electric Capital Portfolio',
          category: 'CATEGORY',
        },
        {
          slug: 'fabric-ventures-portfolio',
          name: 'Fabric Ventures Portfolio',
          category: 'CATEGORY',
        },
        {
          slug: 'framework-ventures-portfolio',
          name: 'Framework Ventures Portfolio',
          category: 'CATEGORY',
        },
        {
          slug: 'galaxy-digital-portfolio',
          name: 'Galaxy Digital Portfolio',
          category: 'CATEGORY',
        },
        {
          slug: 'huobi-capital-portfolio',
          name: 'Huobi Capital Portfolio',
          category: 'CATEGORY',
        },
        {
          slug: 'alameda-research-portfolio',
          name: 'Alameda Research Portfolio',
          category: 'CATEGORY',
        },
        {
          slug: 'a16z-portfolio',
          name: 'a16z Portfolio',
          category: 'CATEGORY',
        },
        {
          slug: '1confirmation-portfolio',
          name: '1Confirmation Portfolio',
          category: 'CATEGORY',
        },
        {
          slug: 'winklevoss-capital-portfolio',
          name: 'Winklevoss Capital Portfolio',
          category: 'CATEGORY',
        },
        {
          slug: 'usv-portfolio',
          name: 'USV Portfolio',
          category: 'CATEGORY',
        },
        {
          slug: 'placeholder-ventures-portfolio',
          name: 'Placeholder Ventures Portfolio',
          category: 'CATEGORY',
        },
        {
          slug: 'pantera-capital-portfolio',
          name: 'Pantera Capital Portfolio',
          category: 'CATEGORY',
        },
        {
          slug: 'multicoin-capital-portfolio',
          name: 'Multicoin Capital Portfolio',
          category: 'CATEGORY',
        },
        {
          slug: 'paradigm-portfolio',
          name: 'Paradigm Portfolio',
          category: 'CATEGORY',
        },
        {
          slug: 'bitcoin-ecosystem',
          name: 'Bitcoin Ecosystem',
          category: 'PLATFORM',
        },
        {
          slug: 'ftx-bankruptcy-estate',
          name: 'FTX Bankruptcy Estate ',
          category: 'CATEGORY',
        },
      ],
      max_supply: 21000000,
      circulating_supply: 19768046,
      total_supply: 19768046,
      is_active: 1,
      infinite_supply: false,
      platform: null,
      cmc_rank: 1,
      is_fiat: 0,
      self_reported_circulating_supply: null,
      self_reported_market_cap: null,
      tvl_ratio: null,
      last_updated: '2024-10-15T17:57:00.000Z',
      quote: {
        USD: {
          price: 67316.37182391781,
          volume_24h: 46877533385.15069,
          volume_change_24h: 17.983,
          percent_change_1h: 0.02598389,
          percent_change_24h: 1.80798462,
          percent_change_7d: 7.45074429,
          percent_change_30d: 11.6742435,
          percent_change_60d: 13.17871647,
          percent_change_90d: 3.84649746,
          market_cap: 1321283776826.3113,
          market_cap_dominance: 57.3285,
          fully_diluted_market_cap: 1403626808302.27,
          tvl: null,
          last_updated: '2024-10-15T17:57:00.000Z',
        },
      },
    },
    1027: {
      id: 1027,
      name: 'Ethereum',
      symbol: 'ETH',
      slug: 'ethereum',
      num_market_pairs: 9414,
      date_added: '2015-08-07T00:00:00.000Z',
      tags: [
        {
          slug: 'pos',
          name: 'PoS',
          category: 'ALGORITHM',
        },
        {
          slug: 'smart-contracts',
          name: 'Smart Contracts',
          category: 'CATEGORY',
        },
        {
          slug: 'ethereum-ecosystem',
          name: 'Ethereum Ecosystem',
          category: 'PLATFORM',
        },
        {
          slug: 'coinbase-ventures-portfolio',
          name: 'Coinbase Ventures Portfolio',
          category: 'CATEGORY',
        },
        {
          slug: 'three-arrows-capital-portfolio',
          name: 'Three Arrows Capital Portfolio',
          category: 'CATEGORY',
        },
        {
          slug: 'polychain-capital-portfolio',
          name: 'Polychain Capital Portfolio',
          category: 'CATEGORY',
        },
        {
          slug: 'binance-labs-portfolio',
          name: 'Binance Labs Portfolio',
          category: 'CATEGORY',
        },
        {
          slug: 'blockchain-capital-portfolio',
          name: 'Blockchain Capital Portfolio',
          category: 'CATEGORY',
        },
        {
          slug: 'boostvc-portfolio',
          name: 'BoostVC Portfolio',
          category: 'CATEGORY',
        },
        {
          slug: 'cms-holdings-portfolio',
          name: 'CMS Holdings Portfolio',
          category: 'CATEGORY',
        },
        {
          slug: 'dcg-portfolio',
          name: 'DCG Portfolio',
          category: 'CATEGORY',
        },
        {
          slug: 'dragonfly-capital-portfolio',
          name: 'DragonFly Capital Portfolio',
          category: 'CATEGORY',
        },
        {
          slug: 'electric-capital-portfolio',
          name: 'Electric Capital Portfolio',
          category: 'CATEGORY',
        },
        {
          slug: 'fabric-ventures-portfolio',
          name: 'Fabric Ventures Portfolio',
          category: 'CATEGORY',
        },
        {
          slug: 'framework-ventures-portfolio',
          name: 'Framework Ventures Portfolio',
          category: 'CATEGORY',
        },
        {
          slug: 'hashkey-capital-portfolio',
          name: 'Hashkey Capital Portfolio',
          category: 'CATEGORY',
        },
        {
          slug: 'kenetic-capital-portfolio',
          name: 'Kenetic Capital Portfolio',
          category: 'CATEGORY',
        },
        {
          slug: 'huobi-capital-portfolio',
          name: 'Huobi Capital Portfolio',
          category: 'CATEGORY',
        },
        {
          slug: 'alameda-research-portfolio',
          name: 'Alameda Research Portfolio',
          category: 'CATEGORY',
        },
        {
          slug: 'a16z-portfolio',
          name: 'a16z Portfolio',
          category: 'CATEGORY',
        },
        {
          slug: '1confirmation-portfolio',
          name: '1Confirmation Portfolio',
          category: 'CATEGORY',
        },
        {
          slug: 'winklevoss-capital-portfolio',
          name: 'Winklevoss Capital Portfolio',
          category: 'CATEGORY',
        },
        {
          slug: 'usv-portfolio',
          name: 'USV Portfolio',
          category: 'CATEGORY',
        },
        {
          slug: 'placeholder-ventures-portfolio',
          name: 'Placeholder Ventures Portfolio',
          category: 'CATEGORY',
        },
        {
          slug: 'pantera-capital-portfolio',
          name: 'Pantera Capital Portfolio',
          category: 'CATEGORY',
        },
        {
          slug: 'multicoin-capital-portfolio',
          name: 'Multicoin Capital Portfolio',
          category: 'CATEGORY',
        },
        {
          slug: 'paradigm-portfolio',
          name: 'Paradigm Portfolio',
          category: 'CATEGORY',
        },
        {
          slug: 'layer-1',
          name: 'Layer 1',
          category: 'CATEGORY',
        },
        {
          slug: 'ftx-bankruptcy-estate',
          name: 'FTX Bankruptcy Estate ',
          category: 'CATEGORY',
        },
      ],
      max_supply: null,
      circulating_supply: 120385428.26335765,
      total_supply: 120385428.26335765,
      is_active: 1,
      infinite_supply: true,
      platform: null,
      cmc_rank: 2,
      is_fiat: 0,
      self_reported_circulating_supply: null,
      self_reported_market_cap: null,
      tvl_ratio: null,
      last_updated: '2024-10-15T17:57:00.000Z',
      quote: {
        USD: {
          price: 2622.8955402509437,
          volume_24h: 21548901663.846832,
          volume_change_24h: 6.9636,
          percent_change_1h: -0.36261277,
          percent_change_24h: -1.56759321,
          percent_change_7d: 5.98598354,
          percent_change_30d: 8.31415399,
          percent_change_60d: -0.51316656,
          percent_change_90d: -24.26757037,
          market_cap: 311063371200.8898,
          market_cap_dominance: 13.497,
          fully_diluted_market_cap: 311063371200.89,
          tvl: null,
          last_updated: '2024-10-15T17:57:00.000Z',
        },
      },
    },
  },
}
